arm_controller:
  joints:
     - joint_s
     - joint_l
     - joint_u
     - joint_r
     - joint_b
     - joint_t
  constraints:
      joint_s: {trajectory: 0.1, goal: 0.1}
      joint_l: {trajectory: 0.1, goal: 0.1}
      joint_u: {trajectory: 0.1, goal: 0.1}
      joint_r: {trajectory: 0.1, goal: 0.1}
      joint_b: {trajectory: 0.1, goal: 0.1}
      joint_t: {trajectory: 0.1, goal: 0.1}
