arm_controller:
  type: position_controllers/JointTrajectoryController
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
  stop_trajectory_duration: 0.5
  state_publish_rate:  50
  action_monitor_rate: 10
